name: shuyo
description: An unofficial, all-in-one utility app for SHU.
publish_to: "none"
version: 0.5.0+21

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^22.0.1
  home_widget: ^0.9.3
  html: ^0.15.6
  http: ^1.6.0
  lunar: ^1.2.20
  package_info_plus: ^10.2.1
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.11.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.12.0
  webview_flutter_wkwebview: ^3.25.1
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/demo/README.md
    - assets/demo/academic/
    - assets/demo/announcements/
    - assets/demo/classroom/
    - assets/demo/course_ratings/
